### ISSUE TITLE
Description causing error

### ISSUE THREAD

**Issue by benwynnjones** [svenanderzen/snapper#1]
When running snapper.sh on Ubuntu 14.04 I get the following error:

```usage: gcloud compute disks snapshot  DISK_NAME [DISK_NAME ...] [optional flags]
ERROR: (gcloud.compute.disks.snapshot) unrecognized arguments:
  backup
  was
  auto
  created
  on
  Tue
  Nov
  15
  19:11:17
  UTC
  2016.
```

If I remove the `--description` line from the final `gcloud compute disks snapshot` call the snapshot is created successfully.

**Comment by svenanderzen** [comment]
Hmm, strange... I have it running on both Ubuntu 14.04, 16.04 and Fedora 24 and haven't had any problems with it so far.

Anyway, I've made an update to the file (a7b73b0d1892f7f19ca1c283d0ab7c15686d361f) and removed the unnecessary `$(command substitutions)` and double quoting so that log files will be printed correctly as well. You'll do best in pulling the new script if you need logging to work properly.

@3evben Please let me know if the problem with the `--description` is gone as well or if I have to dig in to it some more :)

**Comment by svenanderzen** [comment]
Hmm, strange... I have it running on both Ubuntu 14.04, 16.04 and Fedora 24 and haven't had any problems with it so far.

Anyway, I've made an update to the file (a7b73b0) and removed the unnecessary $(command substitutions) and double quoting so that log files will be printed correctly as well. You'll do best in pulling the new script if you need logging to work properly.

@3evben Please let me know if the problem with the --description is gone as well or if I have to dig in to it some more :)
